" Auto-generated unicode_to_latex.vim
cmap <C-c> <Esc>:qa!<CR>

silent! %s/𝔸/\\mathbb\{A\}/gc
silent! %s/𝔹/\\mathbb\{B\}/gc
silent! %s/ℂ/\\mathbb\{C\}/gc
silent! %s/𝔻/\\mathbb\{D\}/gc
silent! %s/𝔼/\\mathbb\{E\}/gc
silent! %s/𝔽/\\mathbb\{F\}/gc
silent! %s/𝔾/\\mathbb\{G\}/gc
silent! %s/ℍ/\\mathbb\{H\}/gc
silent! %s/𝕀/\\mathbb\{I\}/gc
silent! %s/𝕁/\\mathbb\{J\}/gc
silent! %s/𝕂/\\mathbb\{K\}/gc
silent! %s/𝕃/\\mathbb\{L\}/gc
silent! %s/𝕄/\\mathbb\{M\}/gc
silent! %s/ℕ/\\mathbb\{N\}/gc
silent! %s/𝕆/\\mathbb\{O\}/gc
silent! %s/ℙ/\\mathbb\{P\}/gc
silent! %s/ℚ/\\mathbb\{Q\}/gc
silent! %s/ℝ/\\mathbb\{R\}/gc
silent! %s/𝕊/\\mathbb\{S\}/gc
silent! %s/𝕋/\\mathbb\{T\}/gc
silent! %s/𝕌/\\mathbb\{U\}/gc
silent! %s/𝕍/\\mathbb\{V\}/gc
silent! %s/𝕎/\\mathbb\{W\}/gc
silent! %s/𝕏/\\mathbb\{X\}/gc
silent! %s/𝕐/\\mathbb\{Y\}/gc
silent! %s/ℤ/\\mathbb\{Z\}/gc
silent! %s/𝕒/\\mathbb\{a\}/gc
silent! %s/𝕓/\\mathbb\{b\}/gc
silent! %s/𝕔/\\mathbb\{c\}/gc
silent! %s/𝕕/\\mathbb\{d\}/gc
silent! %s/𝕖/\\mathbb\{e\}/gc
silent! %s/𝕗/\\mathbb\{f\}/gc
silent! %s/𝕘/\\mathbb\{g\}/gc
silent! %s/𝕙/\\mathbb\{h\}/gc
silent! %s/𝕚/\\mathbb\{i\}/gc
silent! %s/𝕛/\\mathbb\{j\}/gc
silent! %s/𝕜/\\mathbb\{k\}/gc
silent! %s/𝕝/\\mathbb\{l\}/gc
silent! %s/𝕞/\\mathbb\{m\}/gc
silent! %s/𝕟/\\mathbb\{n\}/gc
silent! %s/𝕠/\\mathbb\{o\}/gc
silent! %s/𝕡/\\mathbb\{p\}/gc
silent! %s/𝕢/\\mathbb\{q\}/gc
silent! %s/𝕣/\\mathbb\{r\}/gc
silent! %s/𝕤/\\mathbb\{s\}/gc
silent! %s/𝕥/\\mathbb\{t\}/gc
silent! %s/𝕦/\\mathbb\{u\}/gc
silent! %s/𝕧/\\mathbb\{v\}/gc
silent! %s/𝕨/\\mathbb\{w\}/gc
silent! %s/𝕩/\\mathbb\{x\}/gc
silent! %s/𝕪/\\mathbb\{y\}/gc
silent! %s/𝕫/\\mathbb\{z\}/gc
silent! %s/𝟘/\\mathbb\{0\}/gc
silent! %s/𝟙/\\mathbbm\{1\}/gc
silent! %s/𝟚/\\mathbb\{2\}/gc
silent! %s/𝟛/\\mathbb\{3\}/gc
silent! %s/𝟜/\\mathbb\{4\}/gc
silent! %s/𝟝/\\mathbb\{5\}/gc
silent! %s/𝟞/\\mathbb\{6\}/gc
silent! %s/𝟟/\\mathbb\{7\}/gc
silent! %s/𝟠/\\mathbb\{8\}/gc
silent! %s/𝟡/\\mathbb\{9\}/gc
silent! %s/Α/\\Alpha/gc
silent! %s/Β/\\Beta/gc
silent! %s/Ψ/\\Psi/gc
silent! %s/Δ/\\Delta/gc
silent! %s/Ε/\\varepsilon/gc
silent! %s/Φ/\\varphi/gc
silent! %s/Γ/\\Gamma/gc
silent! %s/Η/\\Eta/gc
silent! %s/Ι/\\Iota/gc
silent! %s/Ξ/\\Xi/gc
silent! %s/Κ/\\Kappa/gc
silent! %s/Λ/\\Lambda/gc
silent! %s/Μ/\\Mu/gc
silent! %s/Ν/\\Nu/gc
silent! %s/Ο/\\Omicron/gc
silent! %s/Π/\\Pi/gc
silent! %s/Ρ/\\Rho/gc
silent! %s/Σ/\\Sigma/gc
silent! %s/Τ/\\Tau/gc
silent! %s/Θ/\\Theta/gc
silent! %s/Ω/\\Omega/gc
silent! %s/Χ/\\Chi/gc
silent! %s/Υ/\\Upsilon/gc
silent! %s/Ζ/\\Zeta/gc
silent! %s/α/\\alpha/gc
silent! %s/β/\\beta/gc
silent! %s/ψ/\\psi/gc
silent! %s/δ/\\delta/gc
silent! %s/ϵ/\\epsilon/gc
silent! %s/ε/\\varepsilon/gc
silent! %s/ϕ/\\phi/gc
silent! %s/φ/\\varphi/gc
silent! %s/γ/\\gamma/gc
silent! %s/η/\\eta/gc
silent! %s/ι/\\iota/gc
silent! %s/ξ/\\xi/gc
silent! %s/κ/\\kappa/gc
silent! %s/λ/\\lambda/gc
silent! %s/μ/\\mu/gc
silent! %s/ν/\\nu/gc
silent! %s/ο/\\omicron/gc
silent! %s/π/\\pi/gc
silent! %s/ρ/\\rho/gc
silent! %s/σ/\\sigma/gc
silent! %s/τ/\\tau/gc
silent! %s/θ/\\theta/gc
silent! %s/ω/\\omega/gc
silent! %s/υ/\\upsilon/gc
silent! %s/ς/\\varsigma/gc
silent! %s/χ/\\chi/gc
silent! %s/υ/\\upsilon/gc
silent! %s/ζ/\\zeta/gc
silent! %s/𝒜/\\mathcal\{A\}/gc
silent! %s/ℬ/\\mathcal\{B\}/gc
silent! %s/𝒞/\\mathcal\{C\}/gc
silent! %s/𝒟/\\mathcal\{D\}/gc
silent! %s/ℰ/\\mathcal\{E\}/gc
silent! %s/ℱ/\\mathcal\{F\}/gc
silent! %s/𝒢/\\mathcal\{G\}/gc
silent! %s/ℋ/\\mathcal\{H\}/gc
silent! %s/ℐ/\\mathcal\{I\}/gc
silent! %s/𝒥/\\mathcal\{J\}/gc
silent! %s/𝒦/\\mathcal\{K\}/gc
silent! %s/ℒ/\\mathcal\{L\}/gc
silent! %s/ℳ/\\mathcal\{M\}/gc
silent! %s/𝒩/\\mathcal\{N\}/gc
silent! %s/𝒪/\\mathcal\{O\}/gc
silent! %s/𝒫/\\mathcal\{P\}/gc
silent! %s/𝒬/\\mathcal\{Q\}/gc
silent! %s/ℛ/\\mathcal\{R\}/gc
silent! %s/𝒮/\\mathcal\{S\}/gc
silent! %s/𝒯/\\mathcal\{T\}/gc
silent! %s/𝒰/\\mathcal\{U\}/gc
silent! %s/𝒱/\\mathcal\{V\}/gc
silent! %s/𝒲/\\mathcal\{W\}/gc
silent! %s/𝒳/\\mathcal\{X\}/gc
silent! %s/𝒴/\\mathcal\{Y\}/gc
silent! %s/𝒵/\\mathcal\{Z\}/gc
silent! %s/𝒶/\\mathcal\{a\}/gc
silent! %s/𝒷/\\mathcal\{b\}/gc
silent! %s/𝒸/\\mathcal\{c\}/gc
silent! %s/𝒹/\\mathcal\{d\}/gc
silent! %s/ℯ/\\mathcal\{e\}/gc
silent! %s/𝒻/\\mathcal\{f\}/gc
silent! %s/ℊ/\\mathcal\{g\}/gc
silent! %s/𝒽/\\mathcal\{h\}/gc
silent! %s/𝒾/\\mathcal\{i\}/gc
silent! %s/𝒿/\\mathcal\{j\}/gc
silent! %s/𝓀/\\mathcal\{k\}/gc
silent! %s/𝓁/\\mathcal\{l\}/gc
silent! %s/𝓂/\\mathcal\{m\}/gc
silent! %s/𝓃/\\mathcal\{n\}/gc
silent! %s/ℴ/\\mathcal\{o\}/gc
silent! %s/𝓅/\\mathcal\{p\}/gc
silent! %s/𝓆/\\mathcal\{q\}/gc
silent! %s/𝓇/\\mathcal\{r\}/gc
silent! %s/𝓈/\\mathcal\{s\}/gc
silent! %s/𝓉/\\mathcal\{t\}/gc
silent! %s/𝓊/\\mathcal\{u\}/gc
silent! %s/𝓋/\\mathcal\{v\}/gc
silent! %s/𝓌/\\mathcal\{w\}/gc
silent! %s/𝓍/\\mathcal\{x\}/gc
silent! %s/𝓎/\\mathcal\{y\}/gc
silent! %s/𝓏/\\mathcal\{z\}/gc
silent! %s/𝓐/\\mathcal\{A\}/gc
silent! %s/𝓑/\\mathcal\{B\}/gc
silent! %s/𝓒/\\mathcal\{C\}/gc
silent! %s/𝓓/\\mathcal\{D\}/gc
silent! %s/𝓔/\\mathcal\{E\}/gc
silent! %s/𝓕/\\mathcal\{F\}/gc
silent! %s/𝓖/\\mathcal\{G\}/gc
silent! %s/𝓗/\\mathcal\{H\}/gc
silent! %s/𝓘/\\mathcal\{I\}/gc
silent! %s/𝓙/\\mathcal\{J\}/gc
silent! %s/𝓚/\\mathcal\{K\}/gc
silent! %s/𝓛/\\mathcal\{L\}/gc
silent! %s/𝓜/\\mathcal\{M\}/gc
silent! %s/𝓝/\\mathcal\{N\}/gc
silent! %s/𝓞/\\mathcal\{O\}/gc
silent! %s/𝓟/\\mathcal\{P\}/gc
silent! %s/𝓠/\\mathcal\{Q\}/gc
silent! %s/𝓡/\\mathcal\{R\}/gc
silent! %s/𝓢/\\mathcal\{S\}/gc
silent! %s/𝓣/\\mathcal\{T\}/gc
silent! %s/𝓤/\\mathcal\{U\}/gc
silent! %s/𝓥/\\mathcal\{V\}/gc
silent! %s/𝓦/\\mathcal\{W\}/gc
silent! %s/𝓧/\\mathcal\{X\}/gc
silent! %s/𝓨/\\mathcal\{Y\}/gc
silent! %s/𝓩/\\mathcal\{Z\}/gc
silent! %s/𝓪/\\mathcal\{a\}/gc
silent! %s/𝓫/\\mathcal\{b\}/gc
silent! %s/𝓬/\\mathcal\{c\}/gc
silent! %s/𝓭/\\mathcal\{d\}/gc
silent! %s/𝓮/\\mathcal\{e\}/gc
silent! %s/𝓯/\\mathcal\{f\}/gc
silent! %s/𝓰/\\mathcal\{g\}/gc
silent! %s/𝓱/\\mathcal\{h\}/gc
silent! %s/𝓲/\\mathcal\{i\}/gc
silent! %s/𝓳/\\mathcal\{j\}/gc
silent! %s/𝓴/\\mathcal\{k\}/gc
silent! %s/𝓵/\\mathcal\{l\}/gc
silent! %s/𝓶/\\mathcal\{m\}/gc
silent! %s/𝓷/\\mathcal\{n\}/gc
silent! %s/𝓸/\\mathcal\{o\}/gc
silent! %s/𝓹/\\mathcal\{p\}/gc
silent! %s/𝓺/\\mathcal\{q\}/gc
silent! %s/𝓻/\\mathcal\{r\}/gc
silent! %s/𝓼/\\mathcal\{s\}/gc
silent! %s/𝓽/\\mathcal\{t\}/gc
silent! %s/𝓾/\\mathcal\{u\}/gc
silent! %s/𝓿/\\mathcal\{v\}/gc
silent! %s/𝔀/\\mathcal\{w\}/gc
silent! %s/𝔁/\\mathcal\{x\}/gc
silent! %s/𝔂/\\mathcal\{y\}/gc
silent! %s/𝔃/\\mathcal\{z\}/gc
silent! %s/𝔄/\\mathfrak\{A\}/gc
silent! %s/𝔅/\\mathfrak\{B\}/gc
silent! %s/𝔇/\\mathfrak\{D\}/gc
silent! %s/𝔈/\\mathfrak\{E\}/gc
silent! %s/𝔉/\\mathfrak\{F\}/gc
silent! %s/𝔊/\\mathfrak\{G\}/gc
silent! %s/𝔍/\\mathfrak\{J\}/gc
silent! %s/𝔎/\\mathfrak\{K\}/gc
silent! %s/𝔏/\\mathfrak\{L\}/gc
silent! %s/𝔐/\\mathfrak\{M\}/gc
silent! %s/𝔑/\\mathfrak\{N\}/gc
silent! %s/𝔒/\\mathfrak\{O\}/gc
silent! %s/𝔓/\\mathfrak\{P\}/gc
silent! %s/𝔔/\\mathfrak\{Q\}/gc
silent! %s/𝔖/\\mathfrak\{S\}/gc
silent! %s/𝔗/\\mathfrak\{T\}/gc
silent! %s/𝔘/\\mathfrak\{U\}/gc
silent! %s/𝔙/\\mathfrak\{V\}/gc
silent! %s/𝔚/\\mathfrak\{W\}/gc
silent! %s/𝔛/\\mathfrak\{X\}/gc
silent! %s/𝔜/\\mathfrak\{Y\}/gc
silent! %s/𝔞/\\mathfrak\{a\}/gc
silent! %s/𝔟/\\mathfrak\{b\}/gc
silent! %s/𝔠/\\mathfrak\{c\}/gc
silent! %s/𝔡/\\mathfrak\{d\}/gc
silent! %s/𝔢/\\mathfrak\{e\}/gc
silent! %s/𝔣/\\mathfrak\{f\}/gc
silent! %s/𝔤/\\mathfrak\{g\}/gc
silent! %s/𝔥/\\mathfrak\{h\}/gc
silent! %s/𝔦/\\mathfrak\{i\}/gc
silent! %s/𝔧/\\mathfrak\{j\}/gc
silent! %s/𝔨/\\mathfrak\{k\}/gc
silent! %s/𝔩/\\mathfrak\{l\}/gc
silent! %s/𝔪/\\mathfrak\{m\}/gc
silent! %s/𝔫/\\mathfrak\{n\}/gc
silent! %s/𝔬/\\mathfrak\{o\}/gc
silent! %s/𝔭/\\mathfrak\{p\}/gc
silent! %s/𝔮/\\mathfrak\{q\}/gc
silent! %s/𝔯/\\mathfrak\{r\}/gc
silent! %s/𝔰/\\mathfrak\{s\}/gc
silent! %s/𝔱/\\mathfrak\{t\}/gc
silent! %s/𝔲/\\mathfrak\{u\}/gc
silent! %s/𝔳/\\mathfrak\{v\}/gc
silent! %s/𝔴/\\mathfrak\{w\}/gc
silent! %s/𝔵/\\mathfrak\{x\}/gc
silent! %s/𝔶/\\mathfrak\{y\}/gc
silent! %s/𝔷/\\mathfrak\{z\}/gc
silent! %s/↪/\\hookrightarrow/gc
silent! %s/←/\\gets/gc
silent! %s/→/\\to/gc
silent! %s/↦/\\mapsto/gc
silent! %s/⇒/\\Rightarrow/gc
silent! %s/⇐/\\Leftarrow/gc
silent! %s/⇔/\\Leftrightarrow/gc
silent! %s/⇏/\\nRightarrow/gc
silent! %s/↑/\\uparrow/gc
silent! %s/↓/\\downarrow/gc
silent! %s/⇉/\\rightrightarrows/gc
silent! %s/⇓/\\Downarrow/gc
silent! %s/⇀/\\rightharpoonup/gc
silent! %s/⊊/\\subsetneq/gc
silent! %s/≐/\\doteq/gc
silent! %s/∖/\\setminus/gc
silent! %s/⊢/\\vdash/gc
silent! %s/⊣/\\dashv/gc
silent! %s/⊨/\\models/gc
silent! %s/≡/\\equiv/gc
silent! %s/≔/\\coloneqq/gc
silent! %s/≕/\\eqcolon/gc
silent! %s/¬/\\neg/gc
silent! %s/⌊/\\left\\lfloor/gc
silent! %s/⌋/\\right\\rfloor/gc
silent! %s/⌈/\\left\\lceil/gc
silent! %s/⌉/\\right\\rceil/gc
silent! %s/⊕/\\oplus/gc
silent! %s/⨁/\\bigoplus/gc
silent! %s/⊖/\\ominus/gc
silent! %s/⊗/\\otimes/gc
silent! %s/⨂/\\bigotimes/gc
silent! %s/∧/\\wedge/gc
silent! %s/∨/\\vee/gc
silent! %s/≪/\\ll/gc
silent! %s/≫/\\gg/gc
silent! %s/∘/\\circ/gc
silent! %s/⨯/\\times/gc
silent! %s/⋅/\\cdot/gc
silent! %s/∗/\\ast/gc
silent! %s/∅/\\emptyset/gc
silent! %s/∅/\\emptyset/gc
silent! %s/∪/\\cup/gc
silent! %s/∩/\\cap/gc
silent! %s/⊂/\\subset/gc
silent! %s/⊆/\\subseteq/gc
silent! %s/⊄/\\nsubseteq/gc
silent! %s/⊄/\\nsubseteq/gc
silent! %s/⊃/\\supset/gc
silent! %s/⊇/\\supseteq/gc
silent! %s/≠/\\neq/gc
silent! %s/≤/\\leq/gc
silent! %s/≥/\\geq/gc
silent! %s/⊏/\\sqsubset/gc
silent! %s/⊑/\\sqsubseteq/gc
silent! %s/⊑/\\sqsubseteq/gc
silent! %s/⊐/\\sqsupset/gc
silent! %s/⊒/\\sqsupseteq/gc
silent! %s/⊒/\\sqsupseteq/gc
silent! %s/∑/\\sum/gc
silent! %s/∏/\\prod/gc
silent! %s/‖/\\Vert/gc
silent! %s/∣/\\mid/gc
silent! %s/∤/\\nmid/gc
silent! %s/∝/\\propto/gc
silent! %s/∇/\\nabla/gc
silent! %s/∂/\\partial/gc
silent! %s/∼/\\sim/gc
silent! %s/～/\\sim/gc
silent! %s/∫/\\int/gc
silent! %s/∬/\\iint/gc
silent! %s/∭/\\iiint/gc
silent! %s/∮/\\oint/gc
silent! %s/∯/\\oiint/gc
silent! %s/∰/\\oiiint/gc
silent! %s/⊤/\\top/gc
silent! %s/⊥/\\bot/gc
silent! %s/⟂/\\perp/gc
silent! %s/†/\\dagger/gc
silent! %s/ℜ/\\Re/gc
silent! %s/ℑ/\\Im/gc
silent! %s/ℵ/\\aleph/gc
silent! %s/∈/\\in/gc
silent! %s/∉/\\not\\in/gc
silent! %s/∋/\\ni/gc
silent! %s/∌/\\notni/gc
silent! %s/∃/\\exists/gc
silent! %s/∄/\\nexists/gc
silent! %s/∀/\\forall/gc
silent! %s/∞/\\infty/gc
silent! %s/ℓ/\\ell/gc
silent! %s/≅/\\cong/gc
silent! %s/⊔/\\sqcup/gc
silent! %s/÷/\\div/gc
silent! %s/⋮/\\vdots/gc
silent! %s/⋯/\\cdots/gc
silent! %s/…/\\ifmmode\\ldots\\else\\textellipsis\\fi/gc
silent! %s/⋰/\\udots/gc
silent! %s/⋱/\\ddots/gc
silent! %s/∴/\\therefore/gc
silent! %s/ℵ₀/\\aleph_0/gc
silent! %s/ℵ₁/\\aleph_1/gc
silent! %s/📍/\\emoji\{round\-pushpin\}/gc
silent! %s/±/\\pm/gc
silent! %s/≈/\\approx/gc
silent! %s/⋉/\\ltimes/gc
silent! %s/⋊/\\rtimes/gc
silent! %s/‐/\\hyphen/gc
silent! %s/‒/\\figuredash/gc
silent! %s/–/\\endash/gc
silent! %s/—/\\emdash/gc
silent! %s/―/\\horizbar/gc
silent! %s/−/\\minus/gc
